CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR NOT NULL UNIQUE,
    name VARCHAR,
    email VARCHAR NOT NULL UNIQUE,
    birthday DATE,
    CHECK birthday <= current_date
);

CREATE TABLE IF NOT EXISTS mpa (
    mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating VARCHAR
);

CREATE TABLE IF NOT EXISTS films (
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    description VARCHAR(200),
    release_date DATE,
    duration INTEGER,
    mpa_id INTEGER REFERENCES mpa (mpa_id),
    CHECK duration > 0,
    CHECK release_date >= '1895-12-28'
);

CREATE TABLE IF NOT EXISTS friend_relationship (
	user_id INTEGER REFERENCES users(user_id),
	friend_id INTEGER REFERENCES users(user_id),
    CONSTRAINT b PRIMARY KEY(user_id,friend_id)
);

CREATE TABLE IF NOT EXISTS film_likes (
	user_id INTEGER REFERENCES users(user_id),
	film_id INTEGER REFERENCES films(film_id),
    CONSTRAINT a PRIMARY KEY(user_id,film_id)
);

CREATE TABLE IF NOT EXISTS genres (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR
);

CREATE TABLE IF NOT EXISTS film_genre (
 	film_id INTEGER REFERENCES films(film_id),
 	genre_id INTEGER REFERENCES genres(genre_id),
    CONSTRAINT c PRIMARY KEY(film_id,genre_id)
);